chore: support installing from master
Signed-off-by: Sergei Lukianov <me@slukjanov.name>

diff --git a/hhfab b/hhfab
--- a/hhfab
+++ b/hhfab
@@ -94,6 +94,22 @@ findLatestVersion() {
     fi
 }
 
+findMasterVersion() {
+    local master_commit_url="https://api.github.com/repos/githedgehog/fabricator/commits/master?per_page=1"
+    local master_commit_response=""
+    if [ "${HAS_CURL}" == "true" ]; then
+      master_commit_response=$( curl -L --silent --show-error --fail "$master_commit_url" 2>&1 || true )
+    elif [ "${HAS_WGET}" == "true" ]; then
+      master_commit_response=$( wget "$master_commit_url" -O - 2>&1 || true )
+    fi
+    local commit_sha=$( echo "$master_commit_response" | grep '"sha"' | head -1 | sed -E 's/.*"([a-f0-9]{40})".*/\1/g' )
+    if [ "x$commit_sha" == "x" ]; then
+      printf "Could not retrieve the latest master commit SHA from %s: %s\n" "${master_commit_url}" "${master_commit_response}"
+      exit 2
+    fi
+    VERSION="v0-master-${commit_sha:0:9}"
+}
+
 installFile() {
   case "$VERSION" in
     latest) VERSION="v0.41.3";;
@@ -108,18 +124,11 @@ installFile() {
     24.09) VERSION="v0.32.1";;
     24.09.0) VERSION="v0.32.1";;
     beta-1) VERSION="v0.30.3";;
+    dev) echo "Discovering latest dev version..."; findLatestVersion;;
+    master) echo "Discovering latest master commit..."; findMasterVersion;;
   esac
 
   local name="hhfab-${OS}-${ARCH}"
-
-  if [[ "$VERSION" == "v0.19.2" ]]; then
-    name="hhfab"
-  fi
-
-  if [[ "$VERSION" == "dev" ]]; then
-    echo "Discovering latest dev version..."
-    findLatestVersion
-  fi
 
   echo "Downloading $name version $VERSION"
 
